name: Wapiti DAST Scan

on:
  push:
    branches:
      - master

jobs:
  wapiti_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Wapiti
        run: |
          sudo apt-get update
          sudo apt-get install -y wapiti

      - name: Run Wapiti scan
        run: |
          wapiti --url https://developer.mozilla.org/en-US/ -n 5 -b web

      - name: Save Wapiti HTML report
        run: |
          mkdir -p reports
          mv wapiti-report.html reports/

      - name: Upload Wapiti HTML report
        uses: actions/upload-artifact@v2
        with:
          name: wapiti-report
          path: reports/
